name: build-containers

on:
  push:
    branches:
      - master

jobs:
  vultr-exporter:
    name: vultr-exporter
    runs-on: ubuntu-latest
    env:
      REPO: dazwilkin/vultr-exporter
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: docker/setup-buildx-action@v2
      - name: Login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR }}
      - name: Get kernel version
        run: echo "VERSION=$(uname --kernel-release)" >> ${GITHUB_ENV}
      - name: Server
        # id used here in order to provide the output (digest) from this step to cosign sign
        # docker/build-push-action outputs are defined here:
        # https://github.com/docker/build-push-action#outputs
        id: docker-build-push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            TOKEN=${{ secrets.GHCR }}
            VERSION=${{ env.VERSION }}
            COMMIT=${{ github.sha }}
          tags: ghcr.io/${{ env.REPO }}:${{ github.sha }}
          push: true
      - name: Cosign installer
        uses: sigstore/cosign-installer@main
      - name: Write signing key to disk (only needed for `cosign sign --key`)
        run: echo "${{ secrets.SIGNING }}" > ./cosign.key
      - name: Sign container image
        run: |
          cosign sign \
          --key=./cosign.key \
          --annotations="repo=${{ github.repository }}" \
          --annotations="workflow=${{ github.workflow }}" \
          --annotations="commit=${{ github.sha }}" \
          --annotations="version=${{ env.VERSION }}" \
          ghcr.io/${{ env.REPO }}:${{ steps.docker-build-push.outputs.digest }}
        env:
          COSIGN_PASSWORD: ""          
      - name: Revise occurrences of the image
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Actions"

          for FILENAME in "./README.md"
          do
            echo "Replacing: ${REPO}"
            sed \
            --in-place \
            "s|${{ env.REPO }}:[0-9a-f]\{40\}|${{ env.REPO }}:${{ github.sha }}|g" \
            ${FILENAME}
            git add ${FILENAME}
          done
          git commit --message "GitHub Actions update image references"
          git push origin master